config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  root 'pages#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  get 'services' => 'pages#services', as: 'services'
  get 'contact' => 'pages#contact', as: 'contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  validates :title, presence: true,
                      length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "brad",password: "1234",only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @Comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post =Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  private
  def comment_params
    params.require(:comment).permit(:username,:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @title='welcome'
    @content='Welcome to Home page'

  end
  def about
    @title='About'
    @content='Welcome to About page'


  end
  def services
    @title = 'Services'
    @content =' Welcome to Service page'
    @services = ['web design ','web development','SEO']


  end
  def contact
    @title='Contact'
    @content='Contact us at ...'


  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "brad",password: "1234",except: [:index,:show]
  def index
    @posts = Post.all
  end
  def new
    @post = Post.new
  end
  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params);

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end

  end
  def show
    @post = Post.find(params[:id])
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  private
  def post_params
    params.require(:post).permit(:title,:body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
   <div class ="well">
     <p><strong><%= comment.username %>:</strong><%= comment.body %><%= link_to '[X]',[comment.post,comment],
         method: :delete,
         data: {confirm: 'Are you sure?'}%>

     </p>

   </div>

<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for ([@post,@post.comments.build])do |f| %>
    <div class="form-group">
        <%= f.label:username %><br>
        <%= f.text_field(:username,{:class => 'form-control'}) %>
  </div>
  <div class="form-group">
      <%= f.label:body %><br>
      <%= f.text_area(:body,{:class => 'form-control'}) %>
  </div>
  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!--<!DOCTYPE html>
<html>
  <head>
    <title>Railsapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="pt-5">
     <div class="container">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link disabled" href="#">RailsApp</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Home", home_path %> </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "About", about_path %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Services", services_path %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Contact", contact_path %></a>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>-->



<!DOCTYPE html>
<html>
<head>
  <title>Railsapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">RailsApp</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Services", services_path %></li>
            <li><%= link_to "Blog", posts_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Create Post", new_post_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div><!-- /.container -->

</body>
</html>

app/views/pages/about.html.erb
<%= render 'pages/partials/content' %>

app/views/pages/contact.html.erb
<%= render 'pages/partials/content' %>

app/views/pages/index.html.erb
<%= render 'pages/partials/content' %>

app/views/pages/partials/_content.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/pages/services.html.erb
<%= render 'pages/partials/content' %>
<% for @service in @services %>
  <div class = "well">
    <%= @service %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
          <div class= "alert aler-danger"><%= msg %></div>
      <% end %>
      <% end %>

    <div class="form-group">
        <%= f.label:title %><br>
        <%= f.text_field(:title,{:class => 'form-control'}) %>
  </div>
  <div class="form-group">
      <%= f.label:body %><br>
      <%= f.text_area(:body,{:class => 'form-control'}) %>
  </div>
  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Latest Blog Posts</h1>
<% @posts.each do |post| %>
    <div class = "well">
      <h3><%= post.title %></h3>
      <p><%= post.body %></p>
      <%= link_to 'Read More', post_path(post), :class => 'btn btn-default' %>
    </div>

<%end%>

app/views/posts/new.html.erb
<h1>Create Post</h1>
<%=render 'form' %>
<!--<%= form_for :post, url:posts_path do |f| %>
    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |msg| %>
          <div class= "alert aler-danger"><%= msg %></div>
      <% end %>
      <% end %>

    <div class="form-group">
        <%= f.label:title %><br>
        <%= f.text_field(:title,{:class => 'form-control'}) %>
  </div>
  <div class="form-group">
      <%= f.label:body %><br>
      <%= f.text_area(:body,{:class => 'form-control'}) %>
  </div>
  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>-->

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to 'Edit',edit_post_path(@post), :class => 'btn btn-default '%>
<%= link_to 'Delete',post_path(@post),
                     method: :delete,
                     data: {confirm:'Are you sure'},
                     :class => 'btn btn-danger'%>
<%= render 'comments/comments' %>
<%= render 'comments/form' %>